# code: language=toml
# match the name to your Cloudflare worker's name is suggested.
name = "docker-mirror-hammal"
main = "src/index.ts"
compatibility_date = "2024-06-08"

kv_namespaces = [
	# replace the id with your own kv namespace id
	# or provide with the environment variable
	{ binding = "HAMMAL_CACHE", id = "${HAMMAL_CACHE_BINDING_ID}" }
]
